rename "CS01-Kerner.pptx" "Building High Performance Web Apps with Azure.pptx"
rename "CS01_High.mp4" "Building High Performance Web Apps with Azure High Res.mp4"
rename "CS01_Low.mp4" "Building High Performance Web Apps with Azure High Res.mp4"
rename "CS01_High.wmv" "Building High Performance Web Apps with Azure High Res.wmv"
rename "CS01_low.wmv" "Building High Performance Web Apps with Azure High Res.wmv"
rename "CS02-Novick.pptx" "Building Scale Out Database Solutions on SQL Azure.pptx"
rename "CS02_Low.mp4" "Building Scale Out Database Solutions on SQL Azure High Res.mp4"
rename "CS02_Low.wmv" "Building Scale Out Database Solutions on SQL Azure High Res.wmv"
rename "CS02_High.mp4" "Building Scale Out Database Solutions on SQL Azure High Res.mp4"
rename "CS02_High.wmv" "Building Scale Out Database Solutions on SQL Azure High Res.wmv"
rename "CS03-Nakashima.pptx" "Building, Deploying, and Managing Windows Azure.pptx"
rename "CS03_High.mp4" "Building, Deploying, and Managing Windows Azure High Res.mp4"
rename "CS03_Low.mp4" "Building, Deploying, and Managing Windows Azure High Res.mp4"
rename "CS03_Low.wmv" "Building, Deploying, and Managing Windows Azure High Res.wmv"
rename "CS03_High.wmv" "Building, Deploying, and Managing Windows Azure High Res.wmv"
rename "CS04-Anand.pptx" "Composing Applications with AppFabric Services.pptx"
rename "CS04_High.mp4" "Composing Applications with AppFabric Services High Res.mp4"
rename "CS04_Low.mp4" "Composing Applications with AppFabric Services High Res.mp4"
rename "CS04_High.wmv" "Composing Applications with AppFabric Services High Res.wmv"
rename "CS04_Low.wmv" "Composing Applications with AppFabric Services High Res.wmv"
rename "CS05-Khalidi.pptx" "Connecting Cloud & On Premise Apps with Azure Plat.pptx"
rename "CS05_High.mp4" "Connecting Cloud & On Premise Apps with Azure Plat High Res.mp4"
rename "CS05_Low.mp4" "Connecting Cloud & On Premise Apps with Azure Plat High Res.mp4"
rename "CS05_High.wmv" "Connecting Cloud & On Premise Apps with Azure Plat High Res.wmv"
rename "CS05_Low.wmv" "Connecting Cloud & On Premise Apps with Azure Plat High Res.wmv"
rename "Enabling_Low.mp4" "New Scenarios and Apps with Data in the Cloud High Res.mp4"
rename "Enabling_Low.wmv" "New Scenarios and Apps with Data in the Cloud High Res.wmv"
rename "Enabling_High.mp4" "New Scenarios and Apps with Data in the Cloud High Res.mp4"
rename "Enabling_High.wmv" "New Scenarios and Apps with Data in the Cloud High Res.wmv"
rename "CS06-Khosravy-McElroy.pptx" "New Scenarios and Apps with Data in the Cloud.pptx"
rename "datamarket.azure.com" "New Scenarios and Apps with Data in the Cloud.azure.com"
rename "www.powerpivot.com" "New Scenarios and Apps with Data in the Cloud.powerpivot.com"
rename "CS07-Bertocci.pptx" "Identity & Access Control in the Cloud.pptx"
rename "CS07_High.mp4" "Identity & Access Control in the Cloud High Res.mp4"
rename "CS07_Low.mp4" "Identity & Access Control in the Cloud High Res.mp4"
rename "CS07_High.wmv" "Identity & Access Control in the Cloud High Res.wmv"
rename "CS07_Low.wmv" "Identity & Access Control in the Cloud High Res.wmv"
rename "CS08-Russinovich-InsideWindowsAzure.pptx" "Inside Windows Azure.pptx"
rename "CS08_Low.mp4" "Inside Windows Azure High Res.mp4"
rename "CS08_Low.wmv" "Inside Windows Azure High Res.wmv"
rename "CS08_High.mp4" "Inside Windows Azure High Res.mp4"
rename "CS08_High.wmv" "Inside Windows Azure High Res.wmv"
rename "CS09-Srivastava.pptx" "Migrating and Building Apps for Windows Azure.pptx"
rename "CS09_High.mp4" "Migrating and Building Apps for Windows Azure High Res.mp4"
rename "CS09_Low.mp4" "Migrating and Building Apps for Windows Azure High Res.mp4"
rename "CS09_High.wmv" "Migrating and Building Apps for Windows Azure High Res.wmv"
rename "CS09_Low.wmv" "Migrating and Building Apps for Windows Azure High Res.wmv"
rename "CS10-Rajagopalan.pptx" "Open in the Cloud Windows Azure and Java.pptx"
rename "CS10_High.mp4" "Open in the Cloud Windows Azure and Java High Res.mp4"
rename "CS10_Low.mp4" "Open in the Cloud Windows Azure and Java High Res.mp4"
rename "CS10_High.wmv" "Open in the Cloud Windows Azure and Java High Res.wmv"
rename "CS10_Low.wmv" "Open in the Cloud Windows Azure and Java High Res.wmv"
rename "CS11-Haridas.pptx" "Windows Azure Storage Deep Dive.pptx"
rename "CS11_High.mp4" "Windows Azure Storage Deep Dive High Res.mp4"
rename "CS11_High.wmv" "Windows Azure Storage Deep Dive High Res.wmv"
rename "CS11_Low.mp4" "Windows Azure Storage Deep Dive High Res.mp4"
rename "CS11_Low.wmv" "Windows Azure Storage Deep Dive High Res.wmv"
rename "CD01-Russinovich-MemoryManagement.pptx" "Mysteries of Windows Memory Management, Pt 1 of 2.pptx"
rename "CD01_Low.mp4" "Mysteries of Windows Memory Management, Pt 1 of 2 High Res.mp4"
rename "CD01_Low.wmv" "Mysteries of Windows Memory Management, Pt 1 of 2 High Res.wmv"
rename "CD01_High.wmv" "Mysteries of Windows Memory Management, Pt 1 of 2 High Res.wmv"
rename "CD01_High.mp4" "Mysteries of Windows Memory Management, Pt 1 of 2 High Res.mp4"
rename "3211216.aspx" "Mysteries of Windows Memory Management, Pt 1 of 2.aspx"
rename "default.aspx" "Mysteries of Windows Memory Management, Pt 1 of 2.aspx"
rename "CD02-Russinovich-MemoryManagement.pptx" "Mysteries of Windows Memory Management, Pt 2 of 2.pptx"
rename "PhysicalMem_Low.mp4" "Mysteries of Windows Memory Management, Pt 2 of 2 High Res.mp4"
rename "PhysicalMem_High.mp4" "Mysteries of Windows Memory Management, Pt 2 of 2 High Res.mp4"
rename "PhysicalMem_High.wmv" "Mysteries of Windows Memory Management, Pt 2 of 2 High Res.wmv"
rename "PhysicalMem_Low.wmv" "Mysteries of Windows Memory Management, Pt 2 of 2 High Res.wmv"
rename "3211216.aspx" "Mysteries of Windows Memory Management, Pt 2 of 2.aspx"
rename "default.aspx" "Mysteries of Windows Memory Management, Pt 2 of 2.aspx"
rename "CD03-Nachman.pptx" "Optimizing Performance for Silverlight WP7 Apps.pptx"
rename "WP7SL_Low.mp4" "Optimizing Performance for Silverlight WP7 Apps High Res.mp4"
rename "WP7SL_Low.wmv" "Optimizing Performance for Silverlight WP7 Apps High Res.wmv"
rename "CD03_High.mp4" "Optimizing Performance for Silverlight WP7 Apps High Res.mp4"
rename "CD03_High.wmv" "Optimizing Performance for Silverlight WP7 Apps High Res.wmv"
rename "building-high-performance-silverlight-apps-on-windows-phone-7.aspx" "Optimizing Performance for Silverlight WP7 Apps.aspx"
rename "CD04-Hargreaves.pptx" "Building XNA Games for Windows Phone 7.pptx"
rename "CD04_High.mp4" "Building XNA Games for Windows Phone 7 High Res.mp4"
rename "CD04_Low.mp4" "Building XNA Games for Windows Phone 7 High Res.mp4"
rename "CD04_High.wmv" "Building XNA Games for Windows Phone 7 High Res.wmv"
rename "CD04_Low.wmv" "Building XNA Games for Windows Phone 7 High Res.wmv"
rename "CD05-Petkau.pptx" "Analysis and Optimization of XNA Games on WP7.pptx"
rename "CD05_Low.mp4" "Analysis and Optimization of XNA Games on WP7 High Res.mp4"
rename "CD05_High.wmv" "Analysis and Optimization of XNA Games on WP7 High Res.wmv"
rename "CD05_Low.wmv" "Analysis and Optimization of XNA Games on WP7 High Res.wmv"
rename "CD05_High.mp4" "Analysis and Optimization of XNA Games on WP7 High Res.mp4"
rename "CD06_Low.mp4" "Things I Wish I Knew about Building WP7 Apps High Res.mp4"
rename "CD06_Low.wmv" "Things I Wish I Knew about Building WP7 Apps High Res.wmv"
rename "CD06_High.wmv" "Things I Wish I Knew about Building WP7 Apps High Res.wmv"
rename "CD06_High.mp4" "Things I Wish I Knew about Building WP7 Apps High Res.mp4"
rename "CD06-Rodriguez.pptx" "Things I Wish I Knew about Building WP7 Apps.pptx"
rename "building-high-performance-silverlight-apps-on-windows-phone-7.aspx" "Things I Wish I Knew about Building WP7 Apps.aspx"
rename "CD07-Marx.pptx" "Build Windows Phone 7 apps with Windows Azure Plat.pptx"
rename "CD07_High.mp4" "Build Windows Phone 7 apps with Windows Azure Plat High Res.mp4"
rename "CD07_Low.mp4" "Build Windows Phone 7 apps with Windows Azure Plat High Res.mp4"
rename "CD07_High.wmv" "Build Windows Phone 7 apps with Windows Azure Plat High Res.wmv"
rename "CD07_Low.wmv" "Build Windows Phone 7 apps with Windows Azure Plat High Res.wmv"
rename "CD08-Seth.pptx" "Unlocking the JavaScript Opportunity with IE 9.pptx"
rename "CD08_High.mp4" "Unlocking the JavaScript Opportunity with IE 9 High Res.mp4"
rename "CD08_High.wmv" "Unlocking the JavaScript Opportunity with IE 9 High Res.wmv"
rename "CD08_Low.mp4" "Unlocking the JavaScript Opportunity with IE 9 High Res.mp4"
rename "CD08_Low.wmv" "Unlocking the JavaScript Opportunity with IE 9 High Res.wmv"
rename "the-new-javascript-engine-in-internet-explorer-9.aspx" "Unlocking the JavaScript Opportunity with IE 9.aspx"
rename "enhanced-scripting-in-ie9-ecmascript-5-support-and-more.aspx" "Unlocking the JavaScript Opportunity with IE 9.aspx"
rename "s4esdbwz(VS.94).aspx" "Unlocking the JavaScript Opportunity with IE 9.94).aspx"
rename "CD09-Weber.pptx" "Building High Performance HTML 5 Sites with IE 9.pptx"
rename "CD09_High.mp4" "Building High Performance HTML 5 Sites with IE 9 High Res.mp4"
rename "CD09_High.wmv" "Building High Performance HTML 5 Sites with IE 9 High Res.wmv"
rename "CD09_Low.mp4" "Building High Performance HTML 5 Sites with IE 9 High Res.mp4"
rename "CD09_Low.wmv" "Building High Performance HTML 5 Sites with IE 9 High Res.wmv"
rename "CD10-Hilerio.pptx" "Pinned Sites with Internet Explorer 9 & Windows 7.pptx"
rename "CD10_High.mp4" "Pinned Sites with Internet Explorer 9 & Windows 7 High Res.mp4"
rename "CD10_Low.mp4" "Pinned Sites with Internet Explorer 9 & Windows 7 High Res.mp4"
rename "CD10_High.wmv" "Pinned Sites with Internet Explorer 9 & Windows 7 High Res.wmv"
rename "CD10_Low.wmv" "Pinned Sites with Internet Explorer 9 & Windows 7 High Res.wmv"
rename "user-experiences-customizing-pinned-sites.aspx" "Pinned Sites with Internet Explorer 9 & Windows 7.aspx"
rename "gg131029(VS.85).aspx" "Pinned Sites with Internet Explorer 9 & Windows 7.85).aspx"
rename "CD11-Burke.pptx" "3 Screen Coding Sharing code between Windows.pptx"
rename "CD11_Low.mp4" "3 Screen Coding Sharing code between Windows High Res.mp4"
rename "CD11_Low.wmv" "3 Screen Coding Sharing code between Windows High Res.wmv"
rename "CD11_High.mp4" "3 Screen Coding Sharing code between Windows High Res.mp4"
rename "CD11_High.wmv" "3 Screen Coding Sharing code between Windows High Res.wmv"
rename "FT01-Hanselman.pptx" "ASPNET + Packaging + Open Source.pptx"
rename "FT01_Low.mp4" "ASPNET + Packaging + Open Source High Res.mp4"
rename "FT01_High.wmv" "ASPNET + Packaging + Open Source High Res.wmv"
rename "FT01_Low.wmv" "ASPNET + Packaging + Open Source High Res.wmv"
rename "FT01_High.mp4" "ASPNET + Packaging + Open Source High Res.mp4"
rename "FT02-Derstadt-Laverty.pptx" "Code First Development with Entity Framework.pptx"
rename "FT02_Low.mp4" "Code First Development with Entity Framework High Res.mp4"
rename "FT02_Low.wmv" "Code First Development with Entity Framework High Res.wmv"
rename "FT02_High.mp4" "Code First Development with Entity Framework High Res.mp4"
rename "FT02_High.wmv" "Code First Development with Entity Framework High Res.wmv"
rename "odata.org" "Code First Development with Entity Framework.org"
rename "FT03-Castro.pptx" "Inside Some of The Top OData Services.pptx"
rename "FT03_High.mp4" "Inside Some of The Top OData Services High Res.mp4"
rename "FT03_High.wmv" "Inside Some of The Top OData Services High Res.wmv"
rename "ODataSvc_Low.wmv" "Inside Some of The Top OData Services High Res.wmv"
rename "ODataSvc_Low.wmv" "Inside Some of The Top OData Services High Res.wmv"
rename "odata.org" "Inside Some of The Top OData Services.org"
rename "FT04-Block.pptx" "Building Web APIs for the Highly Connected Web.pptx"
rename "FT04_High.mp4" "Building Web APIs for the Highly Connected Web High Res.mp4"
rename "FT04_Low.mp4" "Building Web APIs for the Highly Connected Web High Res.mp4"
rename "FT04_High.wmv" "Building Web APIs for the Highly Connected Web High Res.wmv"
rename "FT04_Low.wmv" "Building Web APIs for the Highly Connected Web High Res.wmv"
rename "FT05-Marks.pptx" "Visual Studio IntelliTrace & Test Impact Analysis.pptx"
rename "FT05_High.mp4" "Visual Studio IntelliTrace & Test Impact Analysis High Res.mp4"
rename "FT05_Low.mp4" "Visual Studio IntelliTrace & Test Impact Analysis High Res.mp4"
rename "FT05_High.wmv" "Visual Studio IntelliTrace & Test Impact Analysis High Res.wmv"
rename "FT05_Low.wmv" "Visual Studio IntelliTrace & Test Impact Analysis High Res.wmv"
rename "FT06-Barnett-deHalleux.pptx" "Better Code Through Smart Assertions & Unit Tests.pptx"
rename "FT06_Low.mp4" "Better Code Through Smart Assertions & Unit Tests High Res.mp4"
rename "FT06_High.wmv" "Better Code Through Smart Assertions & Unit Tests High Res.wmv"
rename "FT06_Low.wmv" "Better Code Through Smart Assertions & Unit Tests High Res.wmv"
rename "FT06_High.mp4" "Better Code Through Smart Assertions & Unit Tests High Res.mp4"
rename "FT07-Remilema.pptx" "Moving a Major Microsoft TFS to the Cloud.pptx"
rename "Lessons_Low.mp4" "Moving a Major Microsoft TFS to the Cloud High Res.mp4"
rename "Lessons_Low.wmv" "Moving a Major Microsoft TFS to the Cloud High Res.wmv"
rename "Lessons_High.mp4" "Moving a Major Microsoft TFS to the Cloud High Res.mp4"
rename "Lessons_High.wmv" "Moving a Major Microsoft TFS to the Cloud High Res.wmv"
rename "FT08-Jacobs.pptx" "Windows Workflow Foundation Futures.pptx"
rename "FT08_High.mp4" "Windows Workflow Foundation Futures High Res.mp4"
rename "FT08_Low.mp4" "Windows Workflow Foundation Futures High Res.mp4"
rename "FT08_High.wmv" "Windows Workflow Foundation Futures High Res.wmv"
rename "FT08_Low.wmv" "Windows Workflow Foundation Futures High Res.wmv"
rename "FT09-Hejlsberg.pptx" "The Future of C# and Visual Basic.pptx"
rename "FT09_High.mp4" "The Future of C# and Visual Basic High Res.mp4"
rename "FT09_Low.mp4" "The Future of C# and Visual Basic High Res.mp4"
rename "FT09_High.wmv" "The Future of C# and Visual Basic High Res.wmv"
rename "FT09_Low.wmv
" "The Future of C# and Visual Basic.wmv
"
rename "FT10-DeSmet.pptx" "LINQ, Take Two Realizing LINQ to Everything Dream.pptx"
rename "FT10_High.mp4" "LINQ, Take Two Realizing LINQ to Everything Dream High Res.mp4"
rename "FT10_Low.mp4" "LINQ, Take Two Realizing LINQ to Everything Dream High Res.mp4"
rename "FT10_Low.wmv" "LINQ, Take Two Realizing LINQ to Everything Dream High Res.wmv"
rename "FT10_High.wmv" "LINQ, Take Two Realizing LINQ to Everything Dream High Res.wmv"
rename "CLI_Low.mp4" "Programming Languages Panel High Res.mp4"
rename "FT11_High.mp4" "Programming Languages Panel High Res.mp4"
rename "FT11_High.wmv" "Programming Languages Panel High Res.wmv"
rename "CLI_Low.wmv" "Programming Languages Panel High Res.wmv"
rename "FT12-Syme.pptx" "The Future of F# Data and Services.pptx"
rename "FT12_High.mp4" "The Future of F# Data and Services High Res.mp4"
rename "FT12_Low.mp4" "The Future of F# Data and Services High Res.mp4"
rename "FT12_High.wmv" "The Future of F# Data and Services High Res.wmv"
rename "FT12_Low.wmv" "The Future of F# Data and Services High Res.wmv"
rename "fsharp.net" "The Future of F# Data and Services.net"
rename "FT13-Sutter.pptx" "Lambdas, Lambdas Everywhere.pptx"
rename "FT13_High.mp4" "Lambdas, Lambdas Everywhere High Res.mp4"
rename "FT13_Low.mp4" "Lambdas, Lambdas Everywhere High Res.mp4"
rename "FT13_High.wmv" "Lambdas, Lambdas Everywhere High Res.wmv"
rename "FT13_Low.wmv" "Lambdas, Lambdas Everywhere High Res.wmv"
rename "Key_Low.wmv" "PDC10 keynotes with Steve Ballmer and Bob Muglia High Res.wmv"
rename "Key_Low.mp4" "PDC10 keynotes with Steve Ballmer and Bob Muglia High Res.mp4"
rename "Key_High.wmv" "PDC10 keynotes with Steve Ballmer and Bob Muglia High Res.wmv"
rename "Key_High.mp4" "PDC10 keynotes with Steve Ballmer and Bob Muglia High Res.mp4"
rename "CS50-Bybee.pptx" "Build Business Apps in the Cloud with CMR Online.pptx"
rename "CS50_AndrewBybee_PDC_MP4_High_1280x720_2500k.mp4" "Build Business Apps in the Cloud with CMR Online High Res.mp4"
rename "CS50_AndrewBybee_PDC_MP4_Low_iPod_480x272_750k.mp4" "Build Business Apps in the Cloud with CMR Online Low Res.mp4"
rename "CS50_AndrewBybee_PDC_WMV_High_1280x720_2500k.wmv" "Build Business Apps in the Cloud with CMR Online High Res.wmv"
rename "CS50_AndrewBybee_PDC_WMV_Low_640x360_1000k.wmv" "Build Business Apps in the Cloud with CMR Online Low Res.wmv"
rename "CS53-Rajagopalan-PHPonAzure.pptx" "Developing PHP Apps on the Windows Azure Plat.pptx"
rename "CS53_VijayRajagopalan_PDC_MP4_High_1280x720_2500k.mp4" "Developing PHP Apps on the Windows Azure Plat High Res.mp4"
rename "CS53_VijayRajagopalan_PDC_MP4_Low_iPod_480x272_750k.mp4" "Developing PHP Apps on the Windows Azure Plat Low Res.mp4"
rename "CS53_VijayRajagopalan_PDC_WMV_High_1280x720_2500k.wmv" "Developing PHP Apps on the Windows Azure Plat High Res.wmv"
rename "CS53_VijayRajagopalan_PDC_WMV_Low_640x360_1000k.wmv" "Developing PHP Apps on the Windows Azure Plat Low Res.wmv"
rename "CD55-Fox.pptx" "Integrating SharePoint with Windows Azure.pptx"
rename "CS55_SteveFox_PDC_MP4_High_1280x720_2500k.mp4" "Integrating SharePoint with Windows Azure High Res.mp4"
rename "CS55_SteveFox_PDC_MP4_Low_iPod_480x272_750k.mp4" "Integrating SharePoint with Windows Azure Low Res.mp4"
rename "CS55_SteveFox_PDC_WMV_High_1280x720_2500k.wmv" "Integrating SharePoint with Windows Azure High Res.wmv"
rename "CS55_SteveFox_PDC_WMV_Low_640x360_1000k.wmv" "Integrating SharePoint with Windows Azure Low Res.wmv"
rename "CS56-Chu.pptx" "Introduction to Database Manager for SQL Azure.pptx"
rename "CS56_EricChu_PDC_MP4_High_1280x720_2500k.mp4" "Introduction to Database Manager for SQL Azure High Res.mp4"
rename "CS56_EricChu_PDC_MP4_Low_iPod_480x272_750k.mp4" "Introduction to Database Manager for SQL Azure Low Res.mp4"
rename "CS56_EricChu_PDC_WMV_High_1280x720_2500k.wmv" "Introduction to Database Manager for SQL Azure High Res.wmv"
rename "CS56_EricChu_PDC_WMV_Low_640x360_1000k.wmv" "Introduction to Database Manager for SQL Azure Low Res.wmv"
rename "CS57-Hu.pptx" "Offline Apps using Sync Framework and SQL Azure.pptx"
rename "CS57_NinaHu_PDC_MP4_High_1280x720_2500k.mp4" "Offline Apps using Sync Framework and SQL Azure High Res.mp4"
rename "CS57_NinaHu_PDC_MP4_Low_iPod_480x272_750k.mp4" "Offline Apps using Sync Framework and SQL Azure Low Res.mp4"
rename "CS57_NinaHu_PDC_WMV_High_1280x720_2500k.wmv" "Offline Apps using Sync Framework and SQL Azure High Res.wmv"
rename "CS57_NinaHu_PDC_WMV_Low_640x360_1000k.wmv" "Offline Apps using Sync Framework and SQL Azure Low Res.wmv"
rename "CS62_JustinSmith_PDC_MP4_High_1280x720_2500k.mp4" "Managing Access Control Service (ACS) Namespaces High Res.mp4"
rename "CS62_JustinSmith_PDC_MP4_Low_iPod_480x272_750k.mp4" "Managing Access Control Service (ACS) Namespaces Low Res.mp4"
rename "CS62_JustinSmith_PDC_WMV_High_1280x720_2500k.wmv" "Managing Access Control Service (ACS) Namespaces High Res.wmv"
rename "CS62_JustinSmith_PDC_WMV_Low_640x360_1000k.wmv" "Managing Access Control Service (ACS) Namespaces Low Res.wmv"
rename "CS64_SreeramNivarthi_PDC_MP4_High_1280x720_2500k.mp4" "Microsoft BizTalk Server 2010 and Roadmap High Res.mp4"
rename "CS64_SreeramNivarthi_PDC_MP4_Low_iPod_480x272_750k.mp4" "Microsoft BizTalk Server 2010 and Roadmap Low Res.mp4"
rename "CS64_SreeramNivarthi_PDC_WMV_High_1280x720_2500k.wmv" "Microsoft BizTalk Server 2010 and Roadmap High Res.wmv"
rename "CS64_SreeramNivarthi_PDC_WMV_Low_640x360_1000k.wmv" "Microsoft BizTalk Server 2010 and Roadmap Low Res.wmv"
rename "CS65-Mayo.pptx" "SharePoint in the Cloud Developing Solutions.pptx"
rename "CS65_ChrisMayo_PDC_MP4_High_1280x720_2500k.mp4" "SharePoint in the Cloud Developing Solutions High Res.mp4"
rename "CS65_ChrisMayo_PDC_MP4_Low_iPod_480x272_750k.mp4" "SharePoint in the Cloud Developing Solutions Low Res.mp4"
rename "CS65_ChrisMayo_PDC_WMV_High_1280x720_2500k.wmv" "SharePoint in the Cloud Developing Solutions High Res.wmv"
rename "CS65_ChrisMayo_PDC_WMV_Low_640x360_1000k.wmv" "SharePoint in the Cloud Developing Solutions Low Res.wmv"
rename "CS66-Mehta-Ciapala.potx" "High Performance Computing to the Cloud.potx"
rename "CS66_RichardCiapala_PDC_MP4_High_1280x720_2500k.mp4" "High Performance Computing to the Cloud High Res.mp4"
rename "CS66_RichardCiapala_PDC_MP4_Low_iPod_480x272_750k.mp4" "High Performance Computing to the Cloud Low Res.mp4"
rename "CS66_RichardCiapala_PDC_WMV_High_1280x720_2500k.wmv" "High Performance Computing to the Cloud High Res.wmv"
rename "CS66_RichardCiapala_PDC_WMV_Low_640x360_1000k.wmv" "High Performance Computing to the Cloud Low Res.wmv"
rename "CD50-Papa.pptx" "Silverlight Tips and ARC Patterns and Practices.pptx"
rename "CD50_JohnPapa_PDC_MP4_High_1280x720_2500k.mp4" "Silverlight Tips and ARC Patterns and Practices High Res.mp4"
rename "CD50_JohnPapa_PDC_MP4_Low_iPod_480x272_750k.mp4" "Silverlight Tips and ARC Patterns and Practices Low Res.mp4"
rename "CD50_JohnPapa_PDC_WMV_High_1280x720_2500k.wmv" "Silverlight Tips and ARC Patterns and Practices High Res.wmv"
rename "CD50_JohnPapa_PDC_WMV_Low_640x360_1000k.wmv" "Silverlight Tips and ARC Patterns and Practices Low Res.wmv"
rename "CD51_JoeMarini_PDC_MP4_High_1280x720_2500k.mp4" "The Rich Mobile Web ??? Today and Tomorrow High Res.mp4"
rename "CD51_JoeMarini_PDC_MP4_Low_iPod_480x272_750k.mp4" "The Rich Mobile Web ??? Today and Tomorrow Low Res.mp4"
rename "CD51_JoeMarini_PDC_WMV_High_1280x720_2500k.wmv" "The Rich Mobile Web ??? Today and Tomorrow High Res.wmv"
rename "CD51_JoeMarini_PDC_WMV_Low_640x360_1000k.wmv" "The Rich Mobile Web ??? Today and Tomorrow Low Res.wmv"
rename "CD52-Ross.pptx" "Best Practices for Cross Browser Web Apps.pptx"
rename "CD52_TonyRoss_PDC_MP4_High_1280x720_2500k.mp4" "Best Practices for Cross Browser Web Apps High Res.mp4"
rename "CD52_TonyRoss_PDC_MP4_Low_iPod_480x272_750k.mp4" "Best Practices for Cross Browser Web Apps Low Res.mp4"
rename "CD52_TonyRoss_PDC_WMV_High_1280x720_2500k.wmv" "Best Practices for Cross Browser Web Apps High Res.wmv"
rename "CD52_TonyRoss_PDC_WMV_Low_640x360_1000k.wmv" "Best Practices for Cross Browser Web Apps Low Res.wmv"
rename "CD53_PatrickDengler_PDC_MP4_High_1280x720_2500k.mp4" "Introducing HTML5 Graphics  Canvas and SVG High Res.mp4"
rename "CD53_PatrickDengler_PDC_MP4_Low_iPod_480x272_750k.mp4" "Introducing HTML5 Graphics  Canvas and SVG Low Res.mp4"
rename "CD53_PatrickDengler_PDC_WMV_High_1280x720_2500k.wmv" "Introducing HTML5 Graphics  Canvas and SVG High Res.wmv"
rename "CD53_PatrickDengler_PDC_WMV_Low_640x360_1000k.wmv" "Introducing HTML5 Graphics  Canvas and SVG Low Res.wmv"
rename "CD54-Luk.pptx" "Making Money with the Windows Phone Market Place.pptx"
rename "CD54_KarenLuk_PDC_MP4_High_1280x720_2500k.mp4" "Making Money with the Windows Phone Market Place High Res.mp4"
rename "CD54_KarenLuk_PDC_MP4_Low_iPod_480x272_750k.mp4" "Making Money with the Windows Phone Market Place Low Res.mp4"
rename "CD54_KarenLuk_PDC_WMV_High_1280x720_2500k.wmv" "Making Money with the Windows Phone Market Place High Res.wmv"
rename "CD54_KarenLuk_PDC_WMV_Low_640x360_1000k.wmv" "Making Money with the Windows Phone Market Place Low Res.wmv"
rename "CD56-Boyd.pptx" "How Every Developer Can Use the GPU in Any App.pptx"
rename "CD56_ChasBoyd_PDC_MP4_High_1280x720_2500k.mp4" "How Every Developer Can Use the GPU in Any App High Res.mp4"
rename "CD56_ChasBoyd_PDC_MP4_Low_iPod_480x272_750k.mp4" "How Every Developer Can Use the GPU in Any App Low Res.mp4"
rename "CD56_ChasBoyd_PDC_WMV_High_1280x720_2500k.wmv" "How Every Developer Can Use the GPU in Any App High Res.wmv"
rename "CD56_ChasBoyd_PDC_WMV_Low_640x360_1000k.wmv" "How Every Developer Can Use the GPU in Any App Low Res.wmv"
rename "CD57-Jain.pptx" "Direct2D and DirectWrite for Hardware Acceleration.pptx"
rename "CD57_MeghaJain_PDC_MP4_High_1280x720_2500k.mp4" "Direct2D and DirectWrite for Hardware Acceleration High Res.mp4"
rename "CD57_MeghaJain_PDC_MP4_Low_iPod_480x272_750k.mp4" "Direct2D and DirectWrite for Hardware Acceleration Low Res.mp4"
rename "CD57_MeghaJain_PDC_WMV_High_1280x720_2500k.wmv" "Direct2D and DirectWrite for Hardware Acceleration High Res.wmv"
rename "CD57_MeghaJain_PDC_WMV_Low_640x360_1000k.wmv" "Direct2D and DirectWrite for Hardware Acceleration Low Res.wmv"
rename "CD58-Boyd.pptx" "High Performance GPU Games and Technical Apps.pptx"
rename "CD58_ChasBoyd_PDC_MP4_High_1280x720_2500k.mp4" "High Performance GPU Games and Technical Apps High Res.mp4"
rename "CD58_ChasBoyd_PDC_MP4_Low_iPod_480x272_750k.mp4" "High Performance GPU Games and Technical Apps Low Res.mp4"
rename "CD58_ChasBoyd_PDC_WMV_High_1280x720_2500k.wmv" "High Performance GPU Games and Technical Apps High Res.wmv"
rename "CD58_ChasBoyd_PDC_WMV_Low_640x360_1000k.wmv" "High Performance GPU Games and Technical Apps Low Res.wmv"
rename "CD59-Sardo.pptx" "HTML5 More Than Just HTML5.pptx"
rename "CD59_GiorgioSardo_PDC_MP4_High_1280x720_2500k.mp4" "HTML5 More Than Just HTML5 High Res.mp4"
rename "CD59_GiorgioSardo_PDC_MP4_Low_iPod_480x272_750k.mp4" "HTML5 More Than Just HTML5 Low Res.mp4"
rename "CD59_GiorgioSardo_PDC_WMV_High_1280x720_2500k.wmv" "HTML5 More Than Just HTML5 High Res.wmv"
rename "CD59_GiorgioSardo_PDC_WMV_Low_640x360_1000k.wmv" "HTML5 More Than Just HTML5 Low Res.wmv"
rename "FT50-Hunter-Nurse.pptx" "Deep Dive into Razor.pptx"
rename "FT50_AndrewNurse_PDC_MP4_High_1280x720_2500k.mp4" "Deep Dive into Razor High Res.mp4"
rename "FT50_AndrewNurse_PDC_MP4_Low_iPod_480x272_750k.mp4" "Deep Dive into Razor Low Res.mp4"
rename "FT50_AndrewNurse_PDC_WMV_High_1280x720_2500k.wmv" "Deep Dive into Razor High Res.wmv"
rename "FT50_AndrewNurse_PDC_WMV_Low_640x360_1000k.wmv" "Deep Dive into Razor Low Res.wmv"
rename "FT51-Khan.pptx" "Software Maintenance and Problem Isolation.pptx"
rename "FT52-Teixeira.pptx" "Parallel Computing Goes Mainstream.pptx"
rename "FT52_SteveTeixeira_PDC_MP4_High_1280x720_2500k.mp4" "Parallel Computing Goes Mainstream High Res.mp4"
rename "FT52_SteveTeixeira_PDC_MP4_Low_iPod_480x272_750k.mp4" "Parallel Computing Goes Mainstream Low Res.mp4"
rename "FT52_SteveTeixeira_PDC_WMV_Low_640x360_1000k.wmv" "Parallel Computing Goes Mainstream Low Res.wmv"
rename "FT52_SteveTeixeira_PDC_WMV_High_1280x720_2500k.wmv" "Parallel Computing Goes Mainstream High Res.wmv"
rename "FT53-Chopra-TestAutomation.pptx" "Test Automation Everywhere.pptx"
rename "FT53_AmitChopra_PDC_MP4_High_1280x720_2500k.mp4" "Test Automation Everywhere High Res.mp4"
rename "FT53_AmitChopra_PDC_MP4_Low_iPod_480x272_750k.mp4" "Test Automation Everywhere Low Res.mp4"
rename "FT53_AmitChopra_PDC_WMV_High_1280x720_2500k.wmv" "Test Automation Everywhere High Res.wmv"
rename "FT53_AmitChopra_PDC_WMV_Low_640x360_1000k.wmv" "Test Automation Everywhere Low Res.wmv"
rename "FT54-Chopra-ContinuousDelivery.pptx" "Continuous DeliveryProduct Backlog to Virtual Lab.pptx"
rename "FT54_AmitChopra_PDC_MP4_High_1280x720_2500k.mp4" "Continuous DeliveryProduct Backlog to Virtual Lab High Res.mp4"
rename "FT54_AmitChopra_PDC_MP4_Low_iPod_480x272_750k.mp4" "Continuous DeliveryProduct Backlog to Virtual Lab Low Res.mp4"
rename "FT54_AmitChopra_PDC_WMV_High_1280x720_2500k.wmv" "Continuous DeliveryProduct Backlog to Virtual Lab High Res.wmv"
rename "FT54_AmitChopra_PDC_WMV_Low_640x360_1000k.wmv" "Continuous DeliveryProduct Backlog to Virtual Lab Low Res.wmv"
rename "FT56_LaurenceMoroney_PDC_MP4_High_1280x720_2500k.mp4" "WebMatrix The Web Reloaded High Res.mp4"
rename "FT56_LaurenceMoroney_PDC_MP4_Low_iPod_480x272_750k.mp4" "WebMatrix The Web Reloaded Low Res.mp4"
rename "FT56_LaurenceMoroney_PDC_WMV_High_1280x720_2500k.wmv" "WebMatrix The Web Reloaded High Res.wmv"
rename "FT56_LaurenceMoroney_PDC_WMV_Low_640x360_1000k.wmv" "WebMatrix The Web Reloaded Low Res.wmv"
rename "FT56-Moroney.pptx" "WebMatrix The Web Reloaded.pptx"
rename "CS51-Wilson.pptx" "Building Engaging Apps with Windows Azure.pptx"
rename "CS51_AdamWilson_PDC_MP4_High_1280x720_2500k.mp4" "Building Engaging Apps with Windows Azure High Res.mp4"
rename "CS51_AdamWilson_PDC_MP4_Low_iPod_480x272_750k.mp4" "Building Engaging Apps with Windows Azure Low Res.mp4"
rename "CS51_AdamWilson_PDC_WMV_High_1280x720_2500k.wmv" "Building Engaging Apps with Windows Azure High Res.wmv"
rename "CS51_AdamWilson_PDC_WMV_Low_640x360_1000k.wmv" "Building Engaging Apps with Windows Azure Low Res.wmv"
rename "datamarket.azure.com" "Building Engaging Apps with Windows Azure.azure.com"
rename "www.powerpivot.com" "Building Engaging Apps with Windows Azure.powerpivot.com"
rename "CS54-Liensberger.pptx" "Inside the Windows Azure Marketplace DataMarket.pptx"
rename "CS54_ChristianLiensberger_PDC_MP4_High_1280x720_2500k.mp4" "Inside the Windows Azure Marketplace DataMarket High Res.mp4"
rename "CS54_ChristianLiensberger_PDC_MP4_Low_iPod_480x272_750k.mp4" "Inside the Windows Azure Marketplace DataMarket Low Res.mp4"
rename "CS54_ChristianLiensberger_PDC_WMV_High_1280x720_2500k.wmv" "Inside the Windows Azure Marketplace DataMarket High Res.wmv"
rename "CS54_ChristianLiensberger_PDC_WMV_Low_640x360_1000k.wmv" "Inside the Windows Azure Marketplace DataMarket Low Res.wmv"
rename "CS58-Cavanagh.pptx" "Introduction to SQL Azure Data Sync.pptx"
rename "CS58_CS58_LiamCavanagh_PDC_MP4_High_1280x720_2500k.mp4" "Introduction to SQL Azure Data Sync High Res.mp4"
rename "CS58_CS58_LiamCavanagh_PDC_MP4_Low_iPod_480x272_750k.mp4" "Introduction to SQL Azure Data Sync Low Res.mp4"
rename "CS58_CS58_LiamCavanagh_PDC_WMV_High_1280x720_2500k.wmv" "Introduction to SQL Azure Data Sync High Res.wmv"
rename "CS58_CS58_LiamCavanagh_PDC_WMV_Low_640x360_1000k.wmv" "Introduction to SQL Azure Data Sync Low Res.wmv"
rename "CS59_NinoBice_PDC_MP4_High_1280x720_2500k.mp4" "Introduction to SQL Azure Reporting High Res.mp4"
rename "CS59_NinoBice_PDC_MP4_Low_iPod_480x272_750k.mp4" "Introduction to SQL Azure Reporting Low Res.mp4"
rename "CS59_NinoBice_PDC_WMV_High_1280x720_2500k.wmv" "Introduction to SQL Azure Reporting High Res.wmv"
rename "CS59_NinoBice_PDC_WMV_Low_640x360_1000k.wmv" "Introduction to SQL Azure Reporting Low Res.wmv"
rename "CS60-Wegner.pptx" "Introduction to Windows Azure AppFabric Caching.pptx"
rename "CS60_WadeWegner_PDC_MP4_High_1280x720_2500k.mp4" "Introduction to Windows Azure AppFabric Caching High Res.mp4"
rename "CS60_WadeWegner_PDC_MP4_Low_iPod_480x272_750k.mp4" "Introduction to Windows Azure AppFabric Caching Low Res.mp4"
rename "CS60_WadeWegner_PDC_WMV_High_1280x720_2500k.wmv" "Introduction to Windows Azure AppFabric Caching High Res.wmv"
rename "CS60_WadeWegner_PDC_WMV_Low_640x360_1000k.wmv" "Introduction to Windows Azure AppFabric Caching Low Res.wmv"
rename "CS61-Wilson.pptx" "Introduction to Windows Azure Marketplace DataMarket.pptx"
rename "CS61_AdamWilson_PDC_MP4_High_1280x720_2500k.mp4" "Introduction to Windows Azure Marketplace DataMarket High Res.mp4"
rename "CS61_AdamWilson_PDC_MP4_Low_iPod_480x272_750k.mp4" "Introduction to Windows Azure Marketplace DataMarket Low Res.mp4"
rename "CS61_AdamWilson_PDC_WMV_High_1280x720_2500k.wmv" "Introduction to Windows Azure Marketplace DataMarket High Res.wmv"
rename "CS61_AdamWilson_PDC_WMV_Low_640x360_1000k.wmv" "Introduction to Windows Azure Marketplace DataMarket Low Res.wmv"
rename "CS63-Vo.pptx" "Inside Windows Azure Virtual Machines.pptx"
rename "CS63_HoiVo_PDC_MP4_High_1280x720_2500k.mp4" "Inside Windows Azure Virtual Machines High Res.mp4"
rename "CS63_HoiVo_PDC_MP4_Low_iPod_480x272_750k.mp4" "Inside Windows Azure Virtual Machines Low Res.mp4"
rename "CS63_HoiVo_PDC_WMV_High_1280x720_2500k.wmv" "Inside Windows Azure Virtual Machines High Res.wmv"
rename "CS63_HoiVo_PDC_WMV_Low_640x360_1000k.wmv" "Inside Windows Azure Virtual Machines Low Res.wmv"
rename "CS67 -Chavez.pptx" "Understanding Windows Azure Connect.pptx"
rename "CS67_AnthonyChavez_PDC_MP4_High_1280x720_2500k.mp4" "Understanding Windows Azure Connect High Res.mp4"
rename "CS67_AnthonyChavez_PDC_MP4_Low_iPod_480x272_750k.mp4" "Understanding Windows Azure Connect Low Res.mp4"
rename "CS67_AnthonyChavez_PDC_WMV_High_1280x720_2500k.wmv" "Understanding Windows Azure Connect High Res.wmv"
rename "CS67_AnthonyChavez_PDC_WMV_Low_640x360_1000k.wmv" "Understanding Windows Azure Connect Low Res.wmv"
rename "CS68-Amiga.pptx" "What's New in Windows Azure.pptx"
rename "CS68_OriAmiga_PDC_MP4_High_1280x720_2500k.mp4" "What's New in Windows Azure High Res.mp4"
rename "CS68_OriAmiga_PDC_MP4_Low_iPod_480x272_750k.mp4" "What's New in Windows Azure Low Res.mp4"
rename "CS68_OriAmiga_PDC_WMV_High_1280x720_2500k.wmv" "What's New in Windows Azure High Res.wmv"
rename "CS68_OriAmiga_PDC_WMV_Low_640x360_1000k.wmv" "What's New in Windows Azure Low Res.wmv"
rename "CS69-Vasters.pptx" "Windows Azure AppFabric Service Bus Futures.pptx"
rename "CS69_ClemensVasters_PDC_MP4_High_1280x720_2500k.mp4" "Windows Azure AppFabric Service Bus Futures High Res.mp4"
rename "CS69_ClemensVasters_PDC_MP4_Low_iPod_480x272_750k.mp4" "Windows Azure AppFabric Service Bus Futures Low Res.mp4"
rename "CS69_ClemensVasters_PDC_WMV_High_1280x720_2500k.wmv" "Windows Azure AppFabric Service Bus Futures High Res.wmv"
rename "CS69_ClemensVasters_PDC_WMV_Low_640x360_1000k.wmv" "Windows Azure AppFabric Service Bus Futures Low Res.wmv"
rename "CS70-Yi.pptx" "What's New in SQL Azure?.pptx"
rename "CS70_SteveYi_PDC_MP4_High_1280x720_2500k.mp4" "What's New in SQL Azure? High Res.mp4"
rename "CS70_SteveYi_PDC_MP4_Low_iPod_480x272_750k.mp4" "What's New in SQL Azure? Low Res.mp4"
rename "CS70_SteveYi_PDC_WMV_High_1280x720_2500k.wmv" "What's New in SQL Azure? High Res.wmv"
rename "CS70_SteveYi_PDC_WMV_Low_640x360_1000k.wmv" "What's New in SQL Azure? Low Res.wmv"
rename "CD60-Relyea.pptx" "WPF Today and Tomorrow.pptx"
rename "CD60_RobRelyea_PDC_MP4_High_1280x720_2500k.mp4" "WPF Today and Tomorrow High Res.mp4"
rename "CD60_RobRelyea_PDC_MP4_Low_iPod_480x272_750k.mp4" "WPF Today and Tomorrow Low Res.mp4"
rename "CD60_RobRelyea_PDC_WMV_High_1280x720_2500k.wmv" "WPF Today and Tomorrow High Res.wmv"
rename "CD60_RobRelyea_PDC_WMV_Low_640x360_1000k.wmv" "WPF Today and Tomorrow Low Res.wmv"
